export const dummyText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et malesuada fames ac turpis. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Sit amet luctus venenatis lectus magna fringilla urna. Egestas congue quisque egestas diam in arcu cursus euismod. Consectetur purus ut faucibus pulvinar elementum integer. Sed turpis tincidunt id aliquet risus feugiat in. Integer eget aliquet nibh praesent tristique magna. Sit amet nisl purus in mollis nunc. At urna condimentum mattis pellentesque id nibh tortor. Elit at imperdiet dui accumsan sit. Nulla malesuada pellentesque elit eget gravida cum. Scelerisque purus semper eget duis at. Id diam maecenas ultricies mi eget mauris. Iaculis eu non diam phasellus vestibulum lorem sed. Volutpat sed cras ornare arcu dui. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis.

Id faucibus nisl tincidunt eget nullam non nisi est sit. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Risus sed vulputate odio ut enim blandit volutpat maecenas. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Nunc mi ipsum faucibus vitae aliquet nec. Volutpat sed cras ornare arcu dui vivamus. Lectus nulla at volutpat diam ut venenatis tellus. Netus et malesuada fames ac turpis egestas. Orci phasellus egestas tellus rutrum tellus pellentesque eu. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Tempor nec feugiat nisl pretium fusce id velit ut tortor. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Et ultrices neque ornare aenean euismod elementum nisi. Volutpat sed cras ornare arcu dui vivamus. Sodales ut eu sem integer vitae. Turpis egestas sed tempus urna.

Mi sit amet mauris commodo quis imperdiet massa tincidunt. Non curabitur gravida arcu ac. Eros in cursus turpis massa tincidunt dui ut. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Id volutpat lacus laoreet non curabitur gravida arcu. Vitae aliquet nec ullamcorper sit amet. Aliquet nibh praesent tristique magna. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Enim facilisis gravida neque convallis a cras. Venenatis a condimentum vitae sapien pellentesque habitant morbi. Posuere ac ut consequat semper. Rhoncus urna neque viverra justo nec. Nisl nisi scelerisque eu ultrices vitae auctor eu.

Scelerisque felis imperdiet proin fermentum leo vel. Quam nulla porttitor massa id neque. Volutpat est velit egestas dui id ornare arcu odio. Gravida neque convallis a cras. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Volutpat lacus laoreet non curabitur gravida arcu. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Mattis enim ut tellus elementum sagittis vitae et leo. Donec et odio pellentesque diam volutpat. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Sit amet consectetur adipiscing elit ut aliquam purus. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Morbi quis commodo odio aenean sed.

Pellentesque sit amet porttitor eget dolor morbi non. Gravida arcu ac tortor dignissim convallis aenean. Accumsan lacus vel facilisis volutpat est velit. Velit euismod in pellentesque massa. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Semper eget duis at tellus at urna condimentum. Habitant morbi tristique senectus et netus et malesuada. Volutpat ac tincidunt vitae semper. Vitae tempus quam pellentesque nec nam aliquam sem et. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Praesent tristique magna sit amet purus gravida. Ultrices eros in cursus turpis massa tincidunt dui. Donec ultrices tincidunt arcu non sodales. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Eu consequat ac felis donec et odio pellentesque diam. Vitae congue eu consequat ac felis.

Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Eget mauris pharetra et ultrices neque. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Amet massa vitae tortor condimentum. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim. Ac turpis egestas sed tempus urna et pharetra. Vulputate odio ut enim blandit volutpat maecenas. Hendrerit gravida rutrum quisque non tellus orci. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Netus et malesuada fames ac. Vitae aliquet nec ullamcorper sit amet risus. Tellus at urna condimentum mattis pellentesque id.

Vitae justo eget magna fermentum iaculis eu non diam phasellus. Vel orci porta non pulvinar neque. Nunc scelerisque viverra mauris in aliquam sem fringilla. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Nam libero justo laoreet sit amet cursus sit. Pulvinar pellentesque habitant morbi tristique senectus. Velit sed ullamcorper morbi tincidunt ornare. Sed id semper risus in hendrerit. Consectetur a erat nam at lectus urna duis. Placerat vestibulum lectus mauris ultrices eros in. Consequat nisl vel pretium lectus quam id leo. Iaculis at erat pellentesque adipiscing. Diam volutpat commodo sed egestas. Condimentum lacinia quis vel eros donec ac odio tempor.

Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Porttitor leo a diam sollicitudin tempor id eu. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Nunc sed velit dignissim sodales. Dolor morbi non arcu risus quis varius quam quisque. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Eu lobortis elementum nibh tellus molestie nunc non. Sagittis purus sit amet volutpat consequat mauris nunc congue. Aliquam ut porttitor leo a. Nam at lectus urna duis. Aliquam ultrices sagittis orci a scelerisque purus semper. Vivamus at augue eget arcu dictum.`;
